### ISSUE TITLE
Async way to publish to interest

### ISSUE THREAD

**Issue by harishajdarevic** [pusher/push-notifications-server-java#13]
Hi guys

Is there a way that we can publish to interest in async manner using this sdk?

Thanks

**Comment by benjamin-tang-pusher** [comment]
I got it publishing async like this. Its got a newFixedThreadPool of 2 and it will call 3 times.

```
package com.benjamin;

import com.pusher.pushnotifications.PushNotifications;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.Map;
import java.util.HashMap;

public class App implements Callable<String> {

    @Override
    public String call() throws Exception {
        String instanceId = "<instance>";
        String secretKey = "<secret>";

        PushNotifications pushNotifications = new PushNotifications(instanceId, secretKey);
        List<String> interests = Arrays.asList("donuts", "pizza");

        Map<String, Map> publishRequest = new HashMap();

        Map<String, String> alert = new HashMap();
        alert.put("alert", "hi");
        Map<String, Map> aps = new HashMap();
        aps.put("aps", alert);
        publishRequest.put("apns", aps);

        Map<String, String> fcmNotification = new HashMap();
        fcmNotification.put("title", "hello");
        fcmNotification.put("body", "Hello world");
        Map<String, Map> fcm = new HashMap();
        fcm.put("notification", fcmNotification);
        publishRequest.put("fcm", fcm);

        System.out.println("Done!");

        return pushNotifications.publishToInterests(interests, publishRequest);
    }

    public static void main(String args[]) {
        ExecutorService executor = Executors.newFixedThreadPool(2);
        List<Future<String>> list = new ArrayList<Future<String>>();
        Callable<String> callable = new App();
        for (int i = 0; i < 3; i++) {
            Future<String> future = executor.submit(callable);
            list.add(future);
        }
        for (Future<String> fut : list) {
            try {
                System.out.println(new Date() + "::" + fut.get());
            } catch (InterruptedException | ExecutionException e) {
                e.printStackTrace();
            }
        }
        executor.shutdown();
    }
}
```

**Comment by benjamin-tang-pusher** [comment]
I've got this example using ExecutorService and Callable, it will publish to three different interests on separate threads:

`public class App implements Callable<String> {

    String interest;
    String message;

    public App(String interest, String message) {
        this.interest = interest;
        this.message = message;
    }

    @Override
    public String call() throws Exception {
        String instanceId = "d2169fce-5202-45d8-9937-cf63aa16f86d";
        String secretKey = "8E9B26187BACC91C68D801F70A7CDFED43850B4A543399E276530A9D14CA8243";

        PushNotifications pushNotifications = new PushNotifications(instanceId, secretKey);
        List<String> interests = Arrays.asList(interest);
        Map<String, Map> publishRequest = new HashMap();

        Map<String, String> webNotification = new HashMap();
        webNotification.put("title", "hello");
        webNotification.put("body", message);
        Map<String, Map> web = new HashMap();
        web.put("notification", webNotification);
        publishRequest.put("web", web);

        return pushNotifications.publishToInterests(interests, publishRequest);
    }

    public static void main(String args[]) {
        ExecutorService executor = Executors.newFixedThreadPool(2);
        List<Future<String>> list = new ArrayList<Future<String>>();
        String[] interestsToPublishTo = { "cake", "donut", "pizza" };
        for (int i = 0; i < interestsToPublishTo.length; i++) {
            Future<String> future = executor.submit(new App(interestsToPublishTo[i], "Asynchronous publishing"));
            list.add(future);
        }
        for (Future<String> fut : list) {
            try {
                System.out.println(new Date() + "::" + fut.get());
            } catch (InterruptedException | ExecutionException e) {
                e.printStackTrace();
            }
        }
        executor.shutdown();
    }
}`

**Comment by benjamin-tang-pusher** [comment]
I've got this example using ExecutorService and Callable, it will publish to three different interests on separate threads:

public class App implements Callable<String> {

    String interest;
    String message;

    public App(String interest, String message) {
        this.interest = interest;
        this.message = message;
    }

    @Override
    public String call() throws Exception {
        String instanceId = "d2169fce-5202-45d8-9937-cf63aa16f86d";
        String secretKey = "xxxxxxxxxxxxxxxx";

        PushNotifications pushNotifications = new PushNotifications(instanceId, secretKey);
        List<String> interests = Arrays.asList(interest);
        Map<String, Map> publishRequest = new HashMap();

        Map<String, String> webNotification = new HashMap();
        webNotification.put("title", "hello");
        webNotification.put("body", message);
        Map<String, Map> web = new HashMap();
        web.put("notification", webNotification);
        publishRequest.put("web", web);

        return pushNotifications.publishToInterests(interests, publishRequest);
    }

    public static void main(String args[]) {
        ExecutorService executor = Executors.newFixedThreadPool(3);
        List<Future<String>> list = new ArrayList<Future<String>>();
       String[] interestsToPublishTo = { "cake", "donut", "pizza" };
        for (int i = 0; i < interestsToPublishTo.length; i++) {
            Future<String> future = executor.submit(new App(interestsToPublishTo[i], "Asynchronous publishing"));
            list.add(future);
        }
        for (Future<String> fut : list) {
            try {
                System.out.println(new Date() + "::" + fut.get());
            } catch (InterruptedException | ExecutionException e) {
                e.printStackTrace();
            }
        }
        executor.shutdown();
    }
}

We don't have a specific publish async method with this library though.
